# Generated by Django 4.0.4 on 2023-02-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_rename_gardian_criminal_guardian_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('image', models.ImageField(default='pexels.jpg', upload_to='profilepics')),
            ],
        ),
    ]
